/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoDatos.InspectorData;
import AccesoDatos.VendedorData;
import Entidades.Inspector;
import Entidades.Vendedor;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abate
 */
public class DatosEmpleados extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloV = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    private DefaultTableModel modeloI = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    
    List<Vendedor> listarVendedor = null;
    List<Inspector> listarInspector = null;
    VendedorData abmVendedorData = new VendedorData();
    InspectorData abmInspectorData = new InspectorData();
    Vendedor tempVendedor = null;
    Inspector tempInspector = null;
    
    
    public DatosEmpleados() {
        initComponents();
        armarTablas();
        cargoCombo();
        camposIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jpVendedores = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfNombreVendedor = new javax.swing.JTextField();
        jbNuevoVendedor = new javax.swing.JButton();
        jtfApellidoVendedor = new javax.swing.JTextField();
        jtfIdVendedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaVendedores = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbEstadoVendedor = new javax.swing.JComboBox<>();
        jbAgregarVendedor = new javax.swing.JButton();
        jbModificarVendedor = new javax.swing.JButton();
        jbCancelarVendedor = new javax.swing.JButton();
        jlCheckNombreVendedor = new javax.swing.JLabel();
        jlCheckApellidoVendedor = new javax.swing.JLabel();
        jpInspectores = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfNombreInspector = new javax.swing.JTextField();
        jbNuevoInspector = new javax.swing.JButton();
        jtfApellidoInspector = new javax.swing.JTextField();
        jtfIdInspector = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbEstadoInspector = new javax.swing.JComboBox<>();
        jbAgregarInspector = new javax.swing.JButton();
        jbModificarInspector = new javax.swing.JButton();
        jbCancelarInspector = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTablaInspectores = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jtfEspecialidadInspector = new javax.swing.JTextField();
        jlCheckNombreInspector = new javax.swing.JLabel();
        jlCheckApellidoInspector = new javax.swing.JLabel();
        jlCheckEspecialidadInspector = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Gestion de Empleados");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ingrese el Nombre:");

        jtfNombreVendedor.setForeground(new java.awt.Color(204, 204, 204));
        jtfNombreVendedor.setText("Nombre");
        jtfNombreVendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNombreVendedorFocusGained(evt);
            }
        });
        jtfNombreVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombreVendedorKeyReleased(evt);
            }
        });

        jbNuevoVendedor.setText("Nuevo Vendedor");
        jbNuevoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoVendedorActionPerformed(evt);
            }
        });

        jtfApellidoVendedor.setForeground(new java.awt.Color(204, 204, 204));
        jtfApellidoVendedor.setText("Apellido");
        jtfApellidoVendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfApellidoVendedorFocusGained(evt);
            }
        });
        jtfApellidoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidoVendedorActionPerformed(evt);
            }
        });
        jtfApellidoVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfApellidoVendedorKeyReleased(evt);
            }
        });

        jtfIdVendedor.setEditable(false);

        jtTablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaVendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaVendedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaVendedores);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Estado:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ID:");

        jbAgregarVendedor.setText("Agregar");
        jbAgregarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarVendedorActionPerformed(evt);
            }
        });

        jbModificarVendedor.setText("Modificar");
        jbModificarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarVendedorActionPerformed(evt);
            }
        });

        jbCancelarVendedor.setText("Cancelar");
        jbCancelarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarVendedorActionPerformed(evt);
            }
        });

        jlCheckNombreVendedor.setText(" ");

        jlCheckApellidoVendedor.setText(" ");

        javax.swing.GroupLayout jpVendedoresLayout = new javax.swing.GroupLayout(jpVendedores);
        jpVendedores.setLayout(jpVendedoresLayout);
        jpVendedoresLayout.setHorizontalGroup(
            jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendedoresLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpVendedoresLayout.createSequentialGroup()
                        .addGroup(jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpVendedoresLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpVendedoresLayout.createSequentialGroup()
                                .addGroup(jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpVendedoresLayout.createSequentialGroup()
                                        .addComponent(jtfNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbNuevoVendedor))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpVendedoresLayout.createSequentialGroup()
                                        .addGap(219, 219, 219)
                                        .addComponent(jbAgregarVendedor)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbModificarVendedor)))
                                .addGap(18, 18, 18)
                                .addComponent(jbCancelarVendedor))
                            .addComponent(jlCheckNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlCheckApellidoVendedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfApellidoVendedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                    .addGroup(jpVendedoresLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jcbEstadoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpVendedoresLayout.setVerticalGroup(
            jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendedoresLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNuevoVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCheckNombreVendedor)
                .addGap(9, 9, 9)
                .addGroup(jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfApellidoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(4, 4, 4)
                .addComponent(jlCheckApellidoVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbEstadoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jpVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarVendedor)
                    .addComponent(jbModificarVendedor)
                    .addComponent(jbCancelarVendedor))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane.addTab("Vendedores", jpVendedores);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ingrese el Nombre:");

        jtfNombreInspector.setForeground(new java.awt.Color(204, 204, 204));
        jtfNombreInspector.setText("Nombre");
        jtfNombreInspector.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNombreInspectorFocusGained(evt);
            }
        });
        jtfNombreInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreInspectorActionPerformed(evt);
            }
        });
        jtfNombreInspector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombreInspectorKeyReleased(evt);
            }
        });

        jbNuevoInspector.setText("Nuevo Inspector");
        jbNuevoInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoInspectorActionPerformed(evt);
            }
        });

        jtfApellidoInspector.setForeground(new java.awt.Color(204, 204, 204));
        jtfApellidoInspector.setText("Apellido");
        jtfApellidoInspector.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfApellidoInspectorFocusGained(evt);
            }
        });
        jtfApellidoInspector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfApellidoInspectorKeyReleased(evt);
            }
        });

        jtfIdInspector.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("ID:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Estado:");

        jbAgregarInspector.setText("Agregar");
        jbAgregarInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarInspectorActionPerformed(evt);
            }
        });

        jbModificarInspector.setText("Modificar");
        jbModificarInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarInspectorActionPerformed(evt);
            }
        });

        jbCancelarInspector.setText("Cancelar");
        jbCancelarInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarInspectorActionPerformed(evt);
            }
        });

        jtTablaInspectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaInspectores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaInspectoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtTablaInspectores);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Especialidad:");

        jtfEspecialidadInspector.setForeground(new java.awt.Color(204, 204, 204));
        jtfEspecialidadInspector.setText("Especialidad");
        jtfEspecialidadInspector.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfEspecialidadInspectorFocusGained(evt);
            }
        });
        jtfEspecialidadInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEspecialidadInspectorActionPerformed(evt);
            }
        });
        jtfEspecialidadInspector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfEspecialidadInspectorKeyReleased(evt);
            }
        });

        jlCheckNombreInspector.setText(" ");

        jlCheckApellidoInspector.setText(" ");

        jlCheckEspecialidadInspector.setText(" ");

        javax.swing.GroupLayout jpInspectoresLayout = new javax.swing.GroupLayout(jpInspectores);
        jpInspectores.setLayout(jpInspectoresLayout);
        jpInspectoresLayout.setHorizontalGroup(
            jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInspectoresLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInspectoresLayout.createSequentialGroup()
                        .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpInspectoresLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfIdInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlCheckNombreInspector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfNombreInspector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                            .addGroup(jpInspectoresLayout.createSequentialGroup()
                                .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlCheckEspecialidadInspector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlCheckApellidoInspector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfEspecialidadInspector, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfApellidoInspector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                .addGap(21, 21, 21)
                                .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpInspectoresLayout.createSequentialGroup()
                                        .addComponent(jbAgregarInspector)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbModificarInspector))
                                    .addComponent(jbNuevoInspector)
                                    .addGroup(jpInspectoresLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbEstadoInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jbCancelarInspector))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpInspectoresLayout.setVerticalGroup(
            jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInspectoresLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNombreInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNuevoInspector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCheckNombreInspector)
                .addGap(9, 9, 9)
                .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfApellidoInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfIdInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCheckApellidoInspector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfEspecialidadInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jcbEstadoInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCheckEspecialidadInspector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpInspectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarInspector)
                    .addComponent(jbModificarInspector)
                    .addComponent(jbCancelarInspector))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane.addTab("Inspectores", jpInspectores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEspecialidadInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEspecialidadInspectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEspecialidadInspectorActionPerformed

    private void jbNuevoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoVendedorActionPerformed
        
        habilitoCampos();
        jbAgregarVendedor.setEnabled(true);
    }//GEN-LAST:event_jbNuevoVendedorActionPerformed

    private void jtfNombreVendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreVendedorKeyReleased
       
        borroFilasVendedor();
        camposIniciales();
        String ingresoNombre = jtfNombreVendedor.getText().toLowerCase();
        listarVendedor = abmVendedorData.listadoVendedor();
        for (Vendedor vend : listarVendedor) {
            String evaluo = vend.getNombre().toLowerCase();
            if (ingresoNombre.isEmpty()) {
                jlCheckNombreVendedor.setEnabled(true);
                jlCheckNombreVendedor.setText("No puede estar vacio");
                jlCheckNombreVendedor.setForeground(Color.red.darker());
                borroFilasVendedor();
                //camposIniciales();
                if (jtfApellidoVendedor.isEnabled()) {
                    jtfApellidoVendedor.setEnabled(false);
                }
                break;
            }else{
                jlCheckNombreVendedor.setEnabled(false);
                jlCheckNombreVendedor.setText("");
            }if (evaluo.contains(ingresoNombre)) {
                if (jbAgregarVendedor.isEnabled()) {
                    jbAgregarVendedor.setEnabled(false);
                }
                modeloV.addRow(new Object[]{vend.getIdVendedor(),vend.getNombre(),vend.getApellido(),vend.getCantidadVentas(),vend.isEstado()});
            }else{
                if (modeloV.getRowCount()==0) {
                    jbNuevoVendedor.setEnabled(true);
                }
            }
        }
        
    }//GEN-LAST:event_jtfNombreVendedorKeyReleased

    private void jbAgregarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarVendedorActionPerformed
       
        String castNombreVendedor = jtfNombreVendedor.getText();
        int valorCombo = jcbEstadoVendedor.getSelectedIndex();
        boolean activo = false;
        if (valorCombo==0) {
            activo=true;
        }
        tempVendedor = new Vendedor();
        tempVendedor.setNombre(castNombreVendedor);
        tempVendedor.setApellido(jtfApellidoVendedor.getText());
        tempVendedor.getCantidadVentas();
        tempVendedor.setEstado(activo);
        abmVendedorData.agregarVendedor(tempVendedor);
        resetearCampos();
        camposIniciales();
    }//GEN-LAST:event_jbAgregarVendedorActionPerformed

    private void jbModificarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarVendedorActionPerformed
        
        tempVendedor = new Vendedor();
        
            int idVendedor = Integer.parseInt(jtfIdVendedor.getText());
            tempVendedor.setIdVendedor(idVendedor);
            tempVendedor.setNombre(jtfNombreVendedor.getText());
            tempVendedor.setApellido(jtfApellidoVendedor.getText());
            int valorEstado = jcbEstadoVendedor.getSelectedIndex();
            boolean activo = false;
            if (valorEstado==0) {
                activo = true;
            }
            tempVendedor.setEstado(activo);
            abmVendedorData.modificarVendedor(tempVendedor);
            resetearCampos();
            borroFilasVendedor();
            modeloV.addRow(new Object[]{tempVendedor.getIdVendedor(),tempVendedor.getNombre(),tempVendedor.getApellido(),tempVendedor.getCantidadVentas(),tempVendedor.isEstado()});
    }//GEN-LAST:event_jbModificarVendedorActionPerformed

    private void jtTablaVendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaVendedoresMouseClicked
        
        jbNuevoVendedor.setEnabled(false);
        int valorVendedor = jtTablaVendedores.getSelectedRow();
        String tomoIdVendedor = String.valueOf(modeloV.getValueAt(valorVendedor, 0));
        String tomoNombreVendedor = String.valueOf(modeloV.getValueAt(valorVendedor, 1));
        String tomoApellidoVendedor = String.valueOf(modeloV.getValueAt(valorVendedor, 2));
        //String tomoCantidadVentas = String.valueOf(modeloV.getValueAt(valorVendedor, 2));
        String tomoEstadoVendedor = String.valueOf(modeloV.getValueAt(valorVendedor, 4));
        jtfIdVendedor.setText(tomoIdVendedor);
        jtfNombreVendedor.setText(tomoNombreVendedor);
        jtfApellidoVendedor.setText(tomoApellidoVendedor);
        if (tomoEstadoVendedor.equals("true")) {
            jcbEstadoVendedor.setSelectedIndex(0);
        } else {
            jcbEstadoVendedor.setSelectedIndex(1);
        }
        jbModificarVendedor.setEnabled(true);
        habilitoCampos();
            
        
    }//GEN-LAST:event_jtTablaVendedoresMouseClicked

    private void jbCancelarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarVendedorActionPerformed
        
        jtfNombreVendedor.setText("");
        jtfApellidoVendedor.setText("");
        jtfIdVendedor.setText("");
        borroFilasVendedor();
        camposIniciales();
    }//GEN-LAST:event_jbCancelarVendedorActionPerformed

    private void jtfApellidoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidoVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfApellidoVendedorActionPerformed

    private void jtfNombreVendedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreVendedorFocusGained
       
        if (jtfNombreVendedor.getText().isEmpty()) {
            jtfNombreVendedor.setText("Nombre");
            jtfNombreVendedor.setForeground(Color.gray);
        } else if( jtfNombreVendedor.getText().equals("Nombre")){
            jtfNombreVendedor.selectAll();
            jtfNombreVendedor.setForeground(Color.black);            
        }
    }//GEN-LAST:event_jtfNombreVendedorFocusGained

    private void jtfApellidoVendedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfApellidoVendedorFocusGained
        
        if (jtfApellidoVendedor.getText().isEmpty()) {
            jtfApellidoVendedor.setText("Apellido");
            jtfApellidoVendedor.setForeground(Color.gray);
        } else if( jtfApellidoVendedor.getText().equals("Apellido")){
            jtfApellidoVendedor.selectAll();
            jtfApellidoVendedor.setForeground(Color.black);
            
            
        }
    }//GEN-LAST:event_jtfApellidoVendedorFocusGained

    private void jbNuevoInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoInspectorActionPerformed
        habilitoCampos();
        jbAgregarInspector.setEnabled(true);
    }//GEN-LAST:event_jbNuevoInspectorActionPerformed

    private void jtfNombreInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreInspectorActionPerformed
        
    }//GEN-LAST:event_jtfNombreInspectorActionPerformed

    private void jtfNombreInspectorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreInspectorKeyReleased
        
        borroFilasInspector();
        camposIniciales();
        String ingresoNombreInspector = jtfNombreInspector.getText().toLowerCase();
        listarInspector = abmInspectorData.listadoInspectoeres();
        for (Inspector insp : listarInspector) {
            String evaluoInsp = insp.getNombre().toLowerCase();
            if (ingresoNombreInspector.isEmpty()) {
                jlCheckNombreInspector.setEnabled(true);
                jlCheckNombreInspector.setText("No puede estar vacio");
                jlCheckNombreInspector.setForeground(Color.red.darker());
                borroFilasInspector();
                camposIniciales();
                if (jtfApellidoInspector.isEnabled()) {
                    jtfApellidoInspector.setEnabled(false);                    
                }
                break;
            }else{
                jlCheckNombreInspector.setEnabled(false);
                jlCheckNombreInspector.setText("");
            
            }if (evaluoInsp.contains(ingresoNombreInspector)) {
                if (jbAgregarInspector.isEnabled()) {
                    jbAgregarInspector.setEnabled(false);
                }
                modeloI.addRow(new Object[]{insp.getIdInspector(),insp.getNombre(),insp.getApellido(),insp.getEspecialidad(),insp.isEstado()});
            }else{
                if (modeloI.getRowCount()==0) {
                    jbNuevoInspector.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_jtfNombreInspectorKeyReleased

    private void jbAgregarInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarInspectorActionPerformed
        
        String castNombreInspector = jtfNombreInspector.getText();
        int valorComboInspector = jcbEstadoInspector.getSelectedIndex();
        boolean activo = false;
        if (valorComboInspector==0) {
            activo=true;
        }
        tempInspector = new Inspector();
        tempInspector.setNombre(castNombreInspector);
        tempInspector.setApellido(jtfApellidoInspector.getText());
        tempInspector.setEspecialidad(jtfEspecialidadInspector.getText());
        tempInspector.setEstado(activo);
        abmInspectorData.agregarInspector(tempInspector);
        resetearCampos();
        camposIniciales();
    }//GEN-LAST:event_jbAgregarInspectorActionPerformed

    private void jbModificarInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarInspectorActionPerformed
        
        tempInspector = new Inspector();
        
            int idInspector = Integer.parseInt(jtfIdInspector.getText());
            tempInspector.setIdInspector(idInspector);
            tempInspector.setNombre(jtfNombreInspector.getText());
            tempInspector.setApellido(jtfApellidoInspector.getText());
            tempInspector.setEspecialidad(jtfEspecialidadInspector.getText());
            int valorEstadoInspector = jcbEstadoInspector.getSelectedIndex();
            boolean activo = false;
            if (valorEstadoInspector==0) {
                activo = true;
            }
            tempInspector.setEstado(activo);
            abmInspectorData.modificarInspector(tempInspector);
            resetearCampos();
            borroFilasInspector();
            modeloI.addRow(new Object[]{tempInspector.getIdInspector(),tempInspector.getNombre(),tempInspector.getApellido(),tempInspector.getEspecialidad(),tempInspector.isEstado()});
                                 
    }//GEN-LAST:event_jbModificarInspectorActionPerformed

    private void jtTablaInspectoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaInspectoresMouseClicked
        
        jbNuevoInspector.setEnabled(false);
        int valorInspector = jtTablaInspectores.getSelectedRow();
        String tomoIdInspector = String.valueOf(modeloI.getValueAt(valorInspector, 0));
        String tomoNombreInspector = String.valueOf(modeloI.getValueAt(valorInspector, 1));
        String tomoApellidoInspector = String.valueOf(modeloI.getValueAt(valorInspector, 2));
        String tomoEspecialidad = String.valueOf(modeloI.getValueAt(valorInspector, 3));
        String tomoEstadoInspector = String.valueOf(modeloI.getValueAt(valorInspector, 4));
        jtfIdInspector.setText(tomoIdInspector);
        jtfNombreInspector.setText(tomoNombreInspector);
        jtfApellidoInspector.setText(tomoApellidoInspector);
        jtfEspecialidadInspector.setText(tomoEspecialidad);
        if (tomoEstadoInspector.equals("true")) {
            jcbEstadoInspector.setSelectedIndex(0);
        } else {
            jcbEstadoInspector.setSelectedIndex(1);
        }
        jbModificarInspector.setEnabled(true);
        habilitoCampos();
    }//GEN-LAST:event_jtTablaInspectoresMouseClicked

    private void jtfNombreInspectorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreInspectorFocusGained
        
        if (jtfNombreInspector.getText().isEmpty()) {
            jtfNombreInspector.setText("Nombre");
            jtfNombreInspector.setForeground(Color.gray);
        } else if (jtfNombreInspector.getText().equals("Nombre")) {
            jtfNombreInspector.selectAll();
            jtfNombreInspector.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtfNombreInspectorFocusGained

    private void jtfApellidoInspectorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfApellidoInspectorFocusGained
        if (jtfApellidoInspector.getText().isEmpty()) {
            jtfApellidoInspector.setText("Apellido");
            jtfApellidoInspector.setForeground(Color.gray);            
        } else if (jtfApellidoInspector.getText().equals("Apellido")) {
            jtfApellidoInspector.selectAll();
            jtfApellidoInspector.setForeground(Color.black);            
        }
    }//GEN-LAST:event_jtfApellidoInspectorFocusGained

    private void jtfEspecialidadInspectorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEspecialidadInspectorFocusGained
        
        if (jtfEspecialidadInspector.getText().isEmpty()) {
            jtfEspecialidadInspector.setText("Especialidad");
            jtfEspecialidadInspector.setForeground(Color.gray);            
        } else if (jtfEspecialidadInspector.getText().equals("Especialidad")) {
            jtfEspecialidadInspector.selectAll();
            jtfEspecialidadInspector.setForeground(Color.black);            
        }
    }//GEN-LAST:event_jtfEspecialidadInspectorFocusGained

    private void jtfApellidoVendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApellidoVendedorKeyReleased
        if (jtfApellidoVendedor.getText().isEmpty()) {
            jlCheckApellidoVendedor.setEnabled(true);
            jlCheckApellidoVendedor.setText("No puede estar vacio");
            jlCheckApellidoVendedor.setForeground(Color.red.darker());
        }else{
            jlCheckApellidoVendedor.setEnabled(false);
            jlCheckApellidoVendedor.setText("");                
            }
            
        
    }//GEN-LAST:event_jtfApellidoVendedorKeyReleased

    private void jtfApellidoInspectorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApellidoInspectorKeyReleased
        if (jtfApellidoInspector.getText().isEmpty()) {
            jlCheckApellidoInspector.setEnabled(true);
            jlCheckApellidoInspector.setText("No puede estar vacio");
            jlCheckApellidoInspector.setForeground(Color.red.darker());
            if (jtfEspecialidadInspector.isEnabled()) {
                jtfEspecialidadInspector.setEnabled(false);
            }
        }else{
            jtfEspecialidadInspector.setEnabled(true);
            jlCheckApellidoInspector.setEnabled(false);
            jlCheckApellidoInspector.setText("");
        }
    }//GEN-LAST:event_jtfApellidoInspectorKeyReleased

    private void jtfEspecialidadInspectorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEspecialidadInspectorKeyReleased
        if (jtfEspecialidadInspector.getText().isEmpty()) {
            jlCheckEspecialidadInspector.setEnabled(true);
            jlCheckEspecialidadInspector.setText("No puede estar vacio");
            jlCheckEspecialidadInspector.setForeground(Color.red.darker());            
        }else{
            jlCheckEspecialidadInspector.setEnabled(false);
            jlCheckEspecialidadInspector.setText("");
        }
    }//GEN-LAST:event_jtfEspecialidadInspectorKeyReleased

    private void jbCancelarInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarInspectorActionPerformed
        
        jtfNombreInspector.setText("");
        jtfApellidoInspector.setText("");
        jtfIdInspector.setText("");
        jtfEspecialidadInspector.setText("");
        borroFilasInspector();
        camposIniciales();
    }//GEN-LAST:event_jbCancelarInspectorActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JButton jbAgregarInspector;
    private javax.swing.JButton jbAgregarVendedor;
    private javax.swing.JButton jbCancelarInspector;
    private javax.swing.JButton jbCancelarVendedor;
    private javax.swing.JButton jbModificarInspector;
    private javax.swing.JButton jbModificarVendedor;
    private javax.swing.JButton jbNuevoInspector;
    private javax.swing.JButton jbNuevoVendedor;
    private javax.swing.JComboBox<String> jcbEstadoInspector;
    private javax.swing.JComboBox<String> jcbEstadoVendedor;
    private javax.swing.JLabel jlCheckApellidoInspector;
    private javax.swing.JLabel jlCheckApellidoVendedor;
    private javax.swing.JLabel jlCheckEspecialidadInspector;
    private javax.swing.JLabel jlCheckNombreInspector;
    private javax.swing.JLabel jlCheckNombreVendedor;
    private javax.swing.JPanel jpInspectores;
    private javax.swing.JPanel jpVendedores;
    private javax.swing.JTable jtTablaInspectores;
    private javax.swing.JTable jtTablaVendedores;
    private javax.swing.JTextField jtfApellidoInspector;
    private javax.swing.JTextField jtfApellidoVendedor;
    private javax.swing.JTextField jtfEspecialidadInspector;
    private javax.swing.JTextField jtfIdInspector;
    private javax.swing.JTextField jtfIdVendedor;
    private javax.swing.JTextField jtfNombreInspector;
    private javax.swing.JTextField jtfNombreVendedor;
    // End of variables declaration//GEN-END:variables
    
    private void armarTablas(){
        modeloV.addColumn("ID");
        modeloV.addColumn("Nombre");
        modeloV.addColumn("Apellido");
        modeloV.addColumn("Cantidad de Ventas");
        modeloV.addColumn("Estado");
        jtTablaVendedores.setModel(modeloV);
        
        modeloI.addColumn("ID");
        modeloI.addColumn("Nombre");
        modeloI.addColumn("Apellido");
        modeloI.addColumn("Especialidad");
        modeloI.addColumn("Estado");
        jtTablaInspectores.setModel(modeloI);
    }
    
    private void camposIniciales(){
        jbNuevoVendedor.setEnabled(false);
        jtfApellidoVendedor.setEnabled(false);
        jtfApellidoVendedor.setText("Apellido");
        jtfApellidoVendedor.setForeground(Color.gray);
        jcbEstadoVendedor.setEnabled(false);
        jbAgregarVendedor.setEnabled(false);
        jbModificarVendedor.setEnabled(false);
        jtfIdVendedor.setEnabled(false);
        jbCancelarVendedor.setEnabled(true);
        jlCheckNombreVendedor.setEnabled(false);
        jlCheckNombreVendedor.setText("");
        jlCheckApellidoVendedor.setEnabled(false);
        jlCheckApellidoVendedor.setText("");
        
        jtfNombreVendedor.requestFocus();
        
        jbNuevoInspector.setEnabled(false);
        jtfApellidoInspector.setEnabled(false);
        jtfApellidoInspector.setText("Apellido");
        jtfApellidoInspector.setForeground(Color.gray);
        jtfEspecialidadInspector.setEnabled(false);
        jcbEstadoInspector.setEnabled(false);
        jbAgregarInspector.setEnabled(false);
        jbModificarInspector.setEnabled(false);
        jtfIdInspector.setEnabled(false);
        jbCancelarInspector.setEnabled(true);
        jlCheckNombreInspector.setEnabled(false);
        jlCheckNombreInspector.setText("");
        jlCheckApellidoInspector.setEnabled(false);
        jlCheckApellidoInspector.setText("");
        jlCheckEspecialidadInspector.setEnabled(false);
        jlCheckEspecialidadInspector.setText("");
        
        jtfNombreInspector.requestFocus();
        
    }
    
    private void cargoCombo(){
        jcbEstadoVendedor.addItem("Activo");
        jcbEstadoVendedor.addItem("Inactivo");
        
        jcbEstadoInspector.addItem("Activo");
        jcbEstadoInspector.addItem("Inactivo");
    }
    
    private void borroFilasVendedor() {
        int num = modeloV.getRowCount() -1;
        for (int i = num; i >= 0; i--) {
            modeloV.removeRow(i);
        }
    }
    
    private void borroFilasInspector() {
        int num = modeloI.getRowCount() - 1;
        for (int i = num; i >= 0; i--) {
            modeloI.removeRow(i);
        }
    }
    
    private void habilitoCampos(){
        jbNuevoVendedor.setEnabled(true);
        jtfApellidoVendedor.setEnabled(true);
        jcbEstadoVendedor.setEnabled(true);
        
        jbNuevoInspector.setEnabled(true);
        jtfApellidoInspector.setEnabled(true);
        jtfEspecialidadInspector.setEnabled(true);
        jcbEstadoInspector.setEnabled(true);
    }
    
    private void resetearCampos(){
        jtfNombreVendedor.requestFocus();
        jtfNombreVendedor.selectAll();
        jtfApellidoVendedor.setText("");
        jtfIdVendedor.setText("");
    }




}
